version: '3.7'

services:
   mysql-standalone:
     image: mysql:8.0
     container_name: mysql-standalone
     ports:
        - "3306"
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: HMS
       MYSQL_PASSWORD: admin
     restart: always
     volumes:
         - ./mysql-dump:/var/lib/mysql

   webapp:
     image: as6779/webapp:v1
     container_name: docker-springboot
     ports:
       - "8086:8086"
     depends_on:
      - mysql-standalone
     restart: always

